---
- name: Set up chibi-miku
  hosts: all
  become: true

  vars:
    required_packages:
      - ansible
      - build-base
      - curl
      - dconf-editor
      - distrobox
      - git
      - gnome-tweaks
      - irqbalance
      - irqbalance-systemd
      - keyd
      - tailscale
      - tailscale-systemd

    laptop_files_dir: "{{ playbook_dir | dirname }}/files/chibi-miku"

    enabled_services:
      - irqbalance.service
      - tailscaled.service

    masked_services:
      - cros-keyboard-map.service
      - iio-sensor-proxy.service

  roles:
    - role: nix

  pre_tasks:
    - name: Ensure required apk packages are installed
      community.general.apk:
        name: "{{ required_packages }}"
        state: present
        update_cache: true

  tasks:
    - name: Mask unwanted systemd services
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        state: stopped
        enabled: false
        masked: true
      loop: "{{ masked_services }}"

    - name: Enable services
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop: "{{ enabled_services }}"

    - name: Ensure keyd configuration directory exists
      ansible.builtin.file:
        path: /etc/keyd
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Install keyd default configuration
      ansible.builtin.copy:
        src: "{{ laptop_files_dir }}/keyd-default.conf"
        dest: /etc/keyd/default.conf
        owner: root
        group: root
        mode: "0644"
      notify: Restart keyd

    - name: Remove generated ChromeOS keyd configuration
      ansible.builtin.file:
        path: /etc/keyd/cros.conf
        state: absent
      notify: Restart keyd

    - name: Ensure udev configuration directory exists
      ansible.builtin.file:
        path: /etc/udev/rules.d
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Install udev rotation definition
      ansible.builtin.copy:
        src: "{{ laptop_files_dir }}/61-cros-ec-accel.rules"
        dest: /etc/udev/rules.d/61-cros-ec-accel.rules
        owner: root
        group: root
        mode: "0644"

    - name: Ensure libwacom configuration directory exists
      ansible.builtin.file:
        path: /etc/libwacom
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Install Wormdingler libwacom tablet definition
      ansible.builtin.copy:
        src: "{{ laptop_files_dir }}/google-wormdingler.tablet"
        dest: /etc/libwacom/google-wormdingler.tablet
        owner: root
        group: root
        mode: "0644"
      notify: Update libwacom db

    - name: Ensure resolved.conf.d directory exists
      ansible.builtin.file:
        path: /etc/systemd/resolved.conf.d
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Install resolved's dnssec config
      ansible.builtin.copy:
        src: "{{ laptop_files_dir }}/resolved-dnssec.conf"
        dest: /etc/systemd/resolved.conf.d/dnssec.conf
        owner: root
        group: root
        mode: "0644"
      notify: Restart systemd-resolved

    - name: Ensure libinput quirks directory exists
      ansible.builtin.file:
        path: /etc/libinput
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Install local libinput overrides
      ansible.builtin.copy:
        src: "{{ laptop_files_dir }}/local-overrides.quirks"
        dest: /etc/libinput/local-overrides.quirks
        owner: root
        group: root
        mode: "0644"

    - name: Install touchscreen-reset sleep hack
      ansible.builtin.copy:
        src: "{{ laptop_files_dir }}/touchscreen-reset.sh"
        dest: /lib/systemd/system-sleep/touchscreen-reset.sh
        owner: root
        group: root
        mode: "0755"

  handlers:
    - name: Restart keyd
      ansible.builtin.systemd_service:
        name: "keyd"
        state: restarted

    - name: Restart systemd-resolved
      ansible.builtin.systemd_service:
        name: "systemd-resolved"
        state: restarted

    - name: Update libwacom db
      ansible.builtin.command: libwacom-update-db
      changed_when: true
