# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/77dd29de-87f8-4154-9dac-b28b2bb129b7";
      fsType = "xfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F77D-A524";
      fsType = "vfat";
    };

  fileSystems."/mnt/archive" =
    { device = "/dev/disk/by-uuid/e31225d0-1879-4242-b054-61c11feaadda";
      # In case of issues changing the configuration just comment fsType
      # https://github.com/NixOS/nixpkgs/issues/113152
      fsType = "btrfs";
      options = [ "subvol=/" "compress=zstd" "nofail" ];
    };

  boot.initrd.luks.devices."enc-archive".device = "/dev/disk/by-uuid/3b236ccb-ec53-4280-8040-00c42feceba8";

  fileSystems."/mnt/data" =
    { device = "/dev/disk/by-uuid/f71560b7-b662-4814-8f26-4e8ca8ae7da4";
      # In case of issues changing the configuration just comment fsType
      # https://github.com/NixOS/nixpkgs/issues/113152
      fsType = "btrfs";
      options = [ "subvol=/" "compress=zstd" "nofail" ];
    };

  boot.initrd.luks.devices."enc-data".device = "/dev/disk/by-uuid/303be66c-74df-41ec-9b5c-c7312bdc582b";

  swapDevices =
    [ { device = "/dev/disk/by-uuid/b14d5664-18e4-429a-a8ef-a98c61275347"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
