{ config, lib, pkgs, ... }:

{
  home.packages = with pkgs; [
    arandr
    bitwarden
    calibre
    chromium
    desktop-file-utils
    discord
    firefox
    gammastep
    gimp
    gnome3.evince
    gnome3.gnome-disk-utility
    gthumb
    inkscape
    kitty
    kotatogram-desktop
    libreoffice-fresh
    lxmenu-data
    ncdu
    pamixer-unstable
    pavucontrol
    pcmanfm
    peek
    qalculate-gtk
    shared-mime-info
    smartmontools
    unstable.mcomix3
    unstable.xdragon
    xarchiver
    xdotool
    xorg.xdpyinfo
    xorg.xhost
    xorg.xkill
    xorg.xset
  ];
}
